<?php

function mymodule_block_info()
{

    $blocks ['myblock'] = array(

        'info' => "my block"

    );
    return $blocks;
}

function mymodule_block_view($delta = '')
{

    switch ($delta) {
        case 'myblock':
            $block['content'] = myblock_view();
            break;
    }
    return $block;

}


function myblock_view()
{

    $url = variable_get('rss_setting');
    $xml = simplexml_load_file($url);

    if (!empty($xml)) {

        $rss_feed = theme('rssblock', array('rows' => $xml));
        return $rss_feed;
    } else {
        $rss_feed['rss_feeds_arguments'] = array(
            '#title' => t('All posts from the last week'),
            '#markup' => t('No posts available.'),
        );
        return $rss_feed;
    }

}

function mymodule_theme()
{
    return array(

        'rssblock' => array(

            'template' => 'rssblock',
            'variables' => array('rows' => array()),
        ),

        'rss_simple' => array(

            'template' => 'rss_simple',
            'variables' => array('simple_feed' => array()),

        )
    );
}


function mymodule_menu()
{

    $items = array();
    $items['rss'] = array(

        'title callback' => 'load_title',
        'description' => 'my rss-reader page',
        'page callback' => 'load_rss',
        'access callback' => TRUE,
    );

    $items['rss/%'] = array(

        'title callback' => 'load_title',
        'description' => 'my rss-reader page',
        'page callback' => 'mymodule_page',
        'page arguments' => array(1),
        'access callback' => TRUE,

    );

    $items['admin/settings/mymodule'] = array(
        'title' => 'Setting RSS',
        'description' => 'Description of mymodule RSS',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('mymodule_admin'),
        'access arguments' => array('administer site configuration'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;

}


function load_title()
{
    $url = variable_get('rss_setting');
    $xml = simplexml_load_file($url);
    $cnltitle = $xml->channel->title;

    return $cnltitle;

}


function load_rss()
{


    $url = variable_get('rss_setting');
    $xml = simplexml_load_file($url);

    if (!empty($xml)) {
        $rss_feed = theme('rssblock', array('rows' => $xml));
        return $rss_feed;
    } else {
        $rss_feed['rss_feeds_arguments'] = array(
            '#title' => t('All posts from the last week'),
            '#markup' => t('No posts available.'),
        );
        return $rss_feed;
    }


}


function mymodule_page($param)
{

    $url = variable_get('rss_setting');
    $xml = simplexml_load_file($url);

    if (!$xml->channel->item[(int)$param]) {
        return false;
    } else {
        $simple = $xml->channel->item[(int)$param];
        return theme('rss_simple', array('simple_feed' => $simple));
    }
}


function mymodule_admin()
{
    $form = array();
    $form['rss_setting'] = array(
        '#type' => 'textfield',
        '#title' => t('My module RSS setting'),
        '#default_value' => variable_get('rss_setting'),
        '#size' => 100,
        '#description' => t("please insert in this field your RSS-link"),
        '#required' => TRUE,
    );
    return system_settings_form($form);
}
